### ISSUE TITLE
Drupal 10 update

### ISSUE THREAD

**Issue by oriolbel** [gigya/drupal8#120]
Hi team,

Now that Drupal 10 core has been released and most of the contrib modules are already compatible or working on the upgrade. 

Is there any step done to have the gigya modules D10 ready?

Many thanks,

Oriol

**Comment by Ynhockey** [comment]
Hi Oriol,

We are exploring this possibility now. We are planning to release full support for Drupal 9.4.x and 9.5.x first though

Thanks,
—Yan..

**Comment by ch-ruetgers-RMH** [comment]
@Ynhockey any idea the Drupal 9.4/9.5 version will become available?

**Comment by Ynhockey** [comment]
Hi @ch-ruetgers-RMH sorry about the late response, version 1.7.0 supports Drupal 9.4/5, and we are expected to release Drupal 10 support by the end of the month, if nothing goes awry.

**Comment by oriolbel** [comment]
Hi @Ynhockey, I've already seen the D10 compatible tag released. Just a minor comment, could you please update the composer.json for the latest 1.8.0 with the right version. I guess this is preventing the package (gigya/gigya-drupal) from being published.

Thanks

**Comment by Ynhockey** [comment]
Hi @oriolbel apologies for the mix-up, it should be OK now.
