### ISSUE TITLE
Error login Drupal 10.2 version

### ISSUE THREAD

**Issue by joseantonio7696** [gigya/drupal8#142]
With the new version of Drupal 10.2.2 the following error occurs when logging in through gigya.

Symfony\Component\DependencyInjection\Exception\AutowiringFailedException: Cannot autowire service "Drupal\gigya_raas\Helper\GigyaRaasHelper|bool": argument "$helper" of method "Drupal\gigya_raas\GigyaController::_construct()", you should configure its value explicitly. en Drupal\Core\Controller\ControllerBase::create() (linea 37 de /var/www/html/docroot/core/lib/Drupal/Core/DependencyInjection/AutowireTrait.php).

**Comment by joseantonio7696** [comment]
Add PR #143

**Comment by Ynhockey** [comment]
PR merged and released in 1.8.2 (being re-released now).
