### ISSUE TITLE
Unable to save Remember Me Session Duration (in seconds)

### ISSUE THREAD

**Issue by nishantkumar155** [gigya/drupal8#41]
when i am going to /admin/config/gigya/raas/session ,

i am unable to save field Remember Me Session Duration (in seconds)

**Comment by nishantkumar155** [comment]
@Ynhockey do you have any idea about how Remember Me Session Duration is working , when value is given as -2,-1 and 0, is there any documentation available for that

**Comment by LeviGigya** [comment]
@nishantkumar155 
https://developers.gigya.com/display/GD/Managing+Session+Expiration

**Comment by Ynhockey** [comment]
@nishantkumar155 Right now only fixed session (>0) and dynamic session (-1) are supported, including for Remember Me. There is indeed a bug that slipped through in the last release, I have already addressed it and updated the develop branch. It will be incorporated into the next release (or serve as the release itself, if there is nothing else).

**Comment by nishantkumar155** [comment]
@Ynhockey Thank you. I appreciate .

**Comment by Ynhockey** [comment]
@nishantkumar155 I have pushed the fix into the master branch, and will make a new minor release (no other fixes/features in this release). Hope this helps.
