### ISSUE TITLE
Plan for Drupal 9

### ISSUE THREAD

**Issue by kkohlbrenner** [gigya/drupal8#58]
Good morning,

Is there a current plan to update the Gigya Drupal 8 distribution to Drupal 9? If so, can someone provide a link to the issue/plan overview?

Thank you,

Kohl Kohlbrenner

**Comment by Ynhockey** [comment]
Hi Kohl,

I have missed this post, but the connector already supports Drupal 9, so I am closing the issue. Please open a new one (or a ticket directly to support) if there is any issue with the Drupal 9 implementation etc.

Thanks!
