### ISSUE TITLE
Connector download issue with composer

### ISSUE THREAD

**Issue by amarlata-tect** [gigya/drupal8#64]
1. I added the repository in project composer.json file from below command.
2. **composer config repositories.gigyadrupal git https://github.com/gigya/drupal8.git**
3. Run **composer require gigya/drupal** or **composer require gigya/drupal8**
4. It showing below error.
     [Composer\Repository\InvalidRepositoryException]
    No valid composer.json was found in any branch or tag of https://github.com/gigya/drupal8.git, could not load a package from it.
5. Is it any option to download the Connector via composer?

**Comment by Ynhockey** [comment]
The Composer file was placed in each individual module folder, that's how it's done on Drupal.org so it was possible to download each package like that. Now that it's not on Drupal.org indeed there is such an issue, so the Composer file needs to be moved to the root folder. I think someone even opened a PR with the change. I will review this and include it in a future release.
