### ISSUE TITLE
Suggestion to rename Composer package name 

### ISSUE THREAD

**Issue by rawdreeg** [gigya/drupal8#80]
Hello there,

Including the package via compose create the folder "drupal" because of the package name gigya/drupal. This could lead to some confusions. Can we rename the package to gigya/gigya or perhaps gigya/gigya_drupal?

I am happy to submit a PR with the change.

Thanks,

R

**Comment by Ynhockey** [comment]
Hi Rawdreeg, sorry for the late reply.

I agree the installation process is a bit problematic in this sense, and we will be looking at making it easier in multiple ways, and consider changing the package name. Can't promise it will happen, but I will update this thread if it does.

**Comment by rawdreeg** [comment]
@Ynhockey Thanks for the reply. What I have done on the project I was leading, I set a custom installer path for the package in composer.json:

I have set up a custom installer path in composer for the gigya/drupal package as follow:


```
"installer-paths": {
            "docroot/core": [
                "type:drupal-core"
            ],
            "docroot/modules/gigya": [
                "gigya/drupal"
            ],
            "docroot/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            ...
```

Maybe updating your documentation would help here :).
